/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IDENT = 35;
  /** RegularExpression Id. */
  int INTLIT = 36;
  /** RegularExpression Id. */
  int ALPHA = 37;
  /** RegularExpression Id. */
  int NUM = 38;
  /** RegularExpression Id. */
  int ALPHANUM = 39;
  /** RegularExpression Id. */
  int FLOATLIT = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"||\"",
    "\"&&\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\";\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"return\"",
    "\"{\"",
    "\"}\"",
    "\"int\"",
    "\"double\"",
    "\"boolean\"",
    "\",\"",
    "\"void\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 33>",
    "<token of kind 34>",
    "<IDENT>",
    "<INTLIT>",
    "<ALPHA>",
    "<NUM>",
    "<ALPHANUM>",
    "<FLOATLIT>",
  };

}
