/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTLIT = 23;
  /** RegularExpression Id. */
  int POSDIGIT = 24;
  /** RegularExpression Id. */
  int ZERO = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int IDENT = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\";\"",
    "\"if\"",
    "\"(\"",
    "\")\"",
    "\"else\"",
    "\"while\"",
    "\"print\"",
    "\"<\"",
    "\"==\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 21>",
    "<token of kind 22>",
    "<INTLIT>",
    "<POSDIGIT>",
    "\"0\"",
    "<DIGIT>",
    "<IDENT>",
  };

}
